config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get "sign_out", :to => "devise/sessions#destroy"
  end
  # devise_scope :user do get "/some/route" => "some_devise_controller" end
  root 'welcome#index'
  get "/pets/:id/report_lost", to: "reports#new", as: "new_report"

  resources :pets, except: [:index]
  resources :reports, except: [:update]
  resources :users, except: [:index]

  get "/reports/:id/contact_user", to: "reports#show_contact_user", as: "show_contact_user"
  post "/reports/:id/contact_user", to: "reports#process_contact_user", as: "process_contact_user"
  patch "/reports/:id", to: 'reports#update', as: "update_report"
end


  # Ensure you have overridden routes for generated controllers in your route.rb.
  # For example:

  #   Rails.application.routes.draw do
  #     devise_for :users, controllers: {
  #       sessions: 'users/sessions'
  #     }
  #   end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pets
  has_many :reports

  validates :email, uniqueness: true, presence: true
  validates :password, length: { minimum: 8}, confirmation: true

  def self.create_from_omniauth(params)
    attributes = {
      email: params['info']['email'],
      password: Devise.friendly_token,
      name: params['info']['name'],
    }

    create(attributes)
  end

  has_many :authentications, class_name: 'UserAuthentication', dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :omniauthable, :omniauth_providers => [:facebook]

  def is user
    self == user
  end

  def first_name
    return name.split(' ')[0] if name      
  end
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

# end

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    create
  end

  def google_oauth2
    create
  end

  def instagram
    create
  end

  private

    def create
      auth_params = request.env["omniauth.auth"]
      provider = AuthenticationProvider.where(name: auth_params.provider).first
      authentication = provider.user_authentications.where(uid: auth_params.uid).first
      existing_user = current_user || User.where('email = ?', auth_params['info']['email']).first

      if authentication
        sign_in_with_existing_authentication(authentication)
      elsif existing_user
        create_authentication_and_sign_in(auth_params, existing_user, provider)
      else
        create_user_and_authentication_and_sign_in(auth_params, provider)
      end
    end

    def sign_in_with_existing_authentication(authentication)
      sign_in_and_redirect(:user, authentication.user)
    end

    def create_authentication_and_sign_in(auth_params, user, provider)
      UserAuthentication.create_from_omniauth(auth_params, user, provider)

      sign_in_and_redirect(:user, user)
    end

    def create_user_and_authentication_and_sign_in(auth_params, provider)
      user = User.create_from_omniauth(auth_params)
      if user.valid?
        create_authentication_and_sign_in(auth_params, user, provider)
      else
        flash[:error] = user.errors.full_messages.first
        redirect_to new_user_registration_url
      end
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users/1
  # GET /users/1.json
  def show
    @pet = Pet.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    return redirect_to @user, alert: "Sorry, you don't have permission to edit this profile." unless current_user == @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
    if @user.update(user_params)
      sign_in(@user, :bypass => true)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :uid, :provider, :password, :password_confirmation, :name, :city, :state, :phone, :oauth_token, :oauth_expires_at)
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email, class: 'form-control custom-form' %>
    </div><br>
    <div>
      <%= f.label :password %><br>
      <%= f.password_field :password, class: 'form-control custom-form' %>
    </div><br>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div><br>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </div><br>
    <div class="field">
      <%= f.label :city %><br>
      <%= f.text_field :city, class: 'form-control' %>
    </div><br>
    <div class="field">
      <%= f.label :state %><br>
      <%= f.text_field :state, class: 'form-control' %>
    </div><br>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone, class: 'form-control' %>
    </div><br>
    <div class="actions">
      <%= f.submit class: "btn btn-primary btn-block" %>
    </div><br />
  </div>
<% end %>

app/views/users/_new_user_pet.html.erb
<% if @user.is current_user %>
	<div class="col-md-2 col-md-offset-10" id="form-btn">
		<%= link_to 'Add Pet', new_pet_path, class: "link-btn-user link-btn btn", id: "userPet", remote: true %>
		</div>
	<div class="col-md-6 col-md-offset-3" id="newPet">
		<%= render 'pets/form_ajax' %>
	</div>
<% end %>

app/views/users/_user_info.html.erb
<div class="col-md-12 panel panel-default" id="info-section">
	<div id="prof-pic">
		<%= gravatar_for @user %>
	</div>

	<h1>
	  <%= @user.name %>
	</h1>

	<p>
	  <strong>Location </strong> <%= @user.city %>, <%= @user.state %>
	</p>
	<% if @user.is current_user %>
	  <%= link_to 'Edit profile', edit_user_path(current_user) %>
	<% end %>
</div>

app/views/users/_user_pets.html.erb
<div class="col-md-12 panel panel-default" id="user-pet-table">
	<div class="col-md-6 col-md-offset-3">
		<% if @user.is current_user %>
			<h2 id="pets-title">Your pets</h2>
		<% else %>
			<h2 id="pets-title"><%= @user.name.split(' ')[0] %>'s Pets</h2>
		<% end %>
	</div>
	<%= render 'new_user_pet' %>
		<table class="table table-hover">
			<thead>
				<tr>
					<th></th>
					<th>Pet Name</th>
					<th>Type</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody id="tableBody">
				<% @user.pets.order(created_at: :desc).each do |pet| %>
					<tr class="petRows custom">
						<td class="clickable">
							<a href="<%= pet_path(pet) %>"><img src="<%= pet.image.url(:thumb) %>" alt="Image of <%= pet.name %>" class="img-thumbnail" /></a>
						</td>
						<td class="clickable"><%= pet.name %></td>
						<td class="clickable"><%= pet.pet_type %></td>
						<td class="group">
							<% if @user.is current_user %>
			          <%= link_to "Edit pet", edit_pet_path(pet), class: "link-btn-user edit-link link-btn"%>
			           <%= link_to 'Remove pet', pet, method: :delete, data: { confirm: 'Are you sure?' },class: "link-btn-user link-btn" %>
			           <% if is_lost? pet.id %>
			           	<%= button_to 'Found', update_report_path(pet.reports.last.id), params: {'report[is_active]' => false }, method: :patch, class: "button found-btn link-btn-user link-btn", :form => { :id => "foundId" }%>
			           	<% else %>
			           		<%= link_to "Report lost", new_report_path(pet.id), class: "link-btn-user lost-btn link-btn", id: "report-lost" %>
			          <% end %>
			        <% end %>
						</td>
					</tr>
			<% end %>
			</tbody>
		</table>
</div>

app/views/users/edit.html.erb
<div class="panel panel-default col-sm-offset-3 col-sm-6">
	<h1>Editing User</h1><br>
	<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container" id="top-container">
	<%= render 'user_info' %>
</div>

<div class="container" id="lower-container">
	<%= render 'user_pets' %>	
</div>