config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get "sign_out", :to => "devise/sessions#destroy"
  end
  # devise_scope :user do get "/some/route" => "some_devise_controller" end
  root 'welcome#index'
  get "/pets/:id/report_lost", to: "reports#new", as: "new_report"

  resources :pets, except: [:index]
  resources :reports, except: [:update]
  resources :users, except: [:index]

  get "/reports/:id/contact_user", to: "reports#show_contact_user", as: "show_contact_user"
  post "/reports/:id/contact_user", to: "reports#process_contact_user", as: "process_contact_user"
  patch "/reports/:id", to: 'reports#update', as: "update_report"
end


  # Ensure you have overridden routes for generated controllers in your route.rb.
  # For example:

  #   Rails.application.routes.draw do
  #     devise_for :users, controllers: {
  #       sessions: 'users/sessions'
  #     }
  #   end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	render :index, :layout => 'welcome_layout'
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="parallax">
	<div class="img parallax__layer parallax__layer--base" id="main-content">	
		<h1 class="splash-custom">Pet ID</h1>
		<h2 class="splash-custom">The fastest way to reunite with the one you love</h2>
		<h2 class="splash-custom">...your furball</h2>
	</div>

<div id="brick">
	<div class="parallax__layer parallax__layer--back" id="boxes">
		<div class="col-sm-4 con left">
      <div class="inner-left inner">
        <h3 class="splash-custom">Found a furry friend?</h3>
        <p class="splash-custom">search our database of lost pets to contact the owner directly</p>
        <p class="splash-custom"><a class="divLink" href="<%= reports_path %>">Search lost pets</a></p>
      </div>
    </div>
		<div class="col-sm-4 con center">
			<div class="inner-center inner">
        <% if user_signed_in? %>
          <h3 class="splash-custom"> Welcome back, <%= current_user.first_name %></h3>
          <%= link_to 'Your Account', current_user, class: 'link-btn splash-btn signup btn' %>
          <%= link_to 'Logout', sign_out_path, class: 'link-btn splash-btn login btn' %>
        <% else %>
				  <h3 class="splash-custom">Login or Sign up</h3>
				  <p class="splash-custom"></p>
          <%= link_to 'Sign up', new_user_registration_path, class: 'link-btn splash-btn signup btn' %>
          <%= link_to 'Login', new_user_session_path, class: 'link-btn splash-btn login btn' %>
        <% end %>
        </div>
      </div>
    <div class="col-sm-4 con right">
			<div class="inner-right inner">
    			<h3 class="splash-custom">Report your pet lost</h3>
    			<p class="splash-custom">to your local community</p>
    			<% if user_signed_in? %>
    				<p><a class="divLink splash-custom" href="<%= user_path(current_user) %>">Login to report your pet</a></p>
    			<% else %>
    				<p><a class="divLink" href="<%= new_user_registration_path %>">Login to report your pet</a></p>
    			<% end %>
			</div>
    </div>
</div>
<div class="col-sm-8 col-sm-offset-2" id="about">
	<h2 class="splash-custom about" id="about-header">About</h2>
		<p class="splash-custom about" id="abt-paragraph">Pet ID helps pet owners find their lost pets. How does it work? A Pet owner simply creates a account and registers their pets. Note that any personal information won't be shared. After siging in and adding a pet, the owner can add a photo and a full description of their pet. Later they can easily update their pets description, and report their pets as lost if needed. After the pet is reported lost, the pet appears within to the lost pet listing. The lost pet listing can be seen by anyone, meaning that a login is not required. The lost pet listing includes lost pet photos as well as the pet's names and the locations where they were lost. Once the pet is identified, email can sent to the owner. The sender's contact information is included within the email sent. The pet owner can then contact the sender and reunite with their pet and update the pet as found. Awesome, Fluffy is heading back home!</p>
	</div>
	</div>