config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get "sign_out", :to => "devise/sessions#destroy"
  end
  # devise_scope :user do get "/some/route" => "some_devise_controller" end
  root 'welcome#index'
  get "/pets/:id/report_lost", to: "reports#new", as: "new_report"

  resources :pets, except: [:index]
  resources :reports, except: [:update]
  resources :users, except: [:index]

  get "/reports/:id/contact_user", to: "reports#show_contact_user", as: "show_contact_user"
  post "/reports/:id/contact_user", to: "reports#process_contact_user", as: "process_contact_user"
  patch "/reports/:id", to: 'reports#update', as: "update_report"
end


  # Ensure you have overridden routes for generated controllers in your route.rb.
  # For example:

  #   Rails.application.routes.draw do
  #     devise_for :users, controllers: {
  #       sessions: 'users/sessions'
  #     }
  #   end

app/models/report.rb
class Report < ActiveRecord::Base
  validates :date_of_loss, presence: true
  validates :user, presence: true
  validates :pet, presence: true
  


  belongs_to :user
  belongs_to :pet



  def self.active_reports
  	@reports = Report.where(is_active: true).order(created_at: :desc)
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include SimpleCaptcha::ControllerHelpers
  before_action :set_report, only: [:show, :edit, :update, :destroy, :show_contact_user, :process_contact_user]
  before_action :authenticate_user!, except: [:index, :show_contact_user, :show]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.active_reports
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @pet = Pet.find(params[:id])

    if is_lost? @pet
      @report_id = @pet.reports.last.id
      redirect_to report_path(@report_id), alert: "There is already a report filed for this pet."
    elsif @pet.user.is current_user
      @report = Report.new
    else
      redirect_to reports_path, alert: "Only the user can report a lost pet."
    end
  end

  # GET /reports/1/edit
  def edit
    if @report.user.is current_user
      @pet = @report.pet
    else
      redirect_to @report, alert: "Sorry, only the user who reported this can edit it."
    end
  end

  # POST /reports
  # POST /reports.json
  def create
    params[:report][:date_of_loss] = Date.strptime(params[:report][:date_of_loss], "%m/%d/%Y")
    @report = Report.new(report_params)
    @report.user = current_user

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to :back, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_contact_user
  end

  def process_contact_user
    if simple_captcha_valid?
      @content = {reporter_name: params[:reporter_name],email: params[:email], phone: params[:phone], message: params[:message]}
      MyMailer.send_found_pet_message(@report,@content).deliver_now
      return redirect_to @report, notice: 'Message sent'
    else
      redirect_to show_contact_user_path(@report), alert: 'Invalid captcha.'
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:reward, :date_of_loss, :location, :user_id, :pet_id, :description, :notes, :is_active)
    end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="row">
      <div class="col-xs-6 col-md-2 field">
        <%= f.label :date_of_loss %>
        <%= f.text_field :date_of_loss, class: "form-control", data: { provide: 'datepicker' } %>
      </div>
      <div class="col-xs-6 col-md-10 field">
        <%= f.label :location %><br>
        <%= f.text_field :location, class: "form-control", placeholder: "Where did you last see your pet?" %>
      </div>
    </div><br>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control", placeholder: "Describe what happened" %>
    </div><br>
    <div class="field">
      <%= f.label :notes %><br>
      <%= f.text_area :notes, class: "form-control", placeholder: "Please note anything someone looking for your pet might need to know." %>
    </div><br>
    <div class="field">
      <%= f.label :reward %><br>
      <%= f.text_field :reward, class: "form-control", placeholder: "If you are offering a reward please write it here; i.e. $100" %>
    </div><br>
    <div class="field">
      <%= f.hidden_field :pet_id, value: @pet.id %><br>
    </div>
    <div class="actions">
      <%= f.submit "Submit report", class: "btn btn-primary btn-block" %>
    </div>

  </div>

<% end %>

app/views/reports/edit.html.erb
<div class="col-sm-offset-3 col-sm-6 panel panel-default">
	<h1>Edit Report Form</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @report %> 
</div>

app/views/reports/index.html.erb
<div class="panel panel-default top-pan">
  <h1 id="report-h1">Lost Pet Reports</h1>
</div>
<div class="panel panel-default custom col-sm-12">
  <table class="table-striped display table-responsive" id="table_id">
      <thead>
        <tr>
          <th>Image</th>
          <th>Pet Name</th>
          <th>Location</th>
          <th>Time Reported</th>
          <th>Contact Owner</th>
          <th>Pet Details</th>
        </tr>
      </thead>
    <tbody>
      <% @reports.each do |report| %>
        <tr>
          <td>
            <img class="media-object custom-dog thumbnail" src="<%= report.pet.image.url(:thumb) %>" alt="placeholder dog">
          </td>
          <td><%= report.pet.name %></td>
          <td><%= report.location %></td>
          <td><%= time_ago_in_words(report.updated_at) %></td>
          <td><%= link_to 'Contact Owner', show_contact_user_path(report.id) %></td>
          <td><%= link_to 'Pet Details', report %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reports/new.html.erb
<div class="panel panel-default col-sm-offset-1 col-sm-10">
<h1>New Report</h1><br>

<%= render 'form' %>

</div>

app/views/reports/show.html.erb
<div class="container">

<div class="jumbotron">
  <div class="row">
  <div class="col-xs-6 col-md-4">
    <%= image_tag @report.pet.image.url(:medium), class: "thumbnail img-responsive" %>
  </div>
    <div class="col-xs-6 col-md-8">
      <div class="thumbnail">
        <div class="caption">
          <p><strong>Name:</strong> <%= @report.pet.name %></p>
          <p><strong>Type:</strong> <%= @report.pet.pet_type %></p>
          <p><strong>Breed:</strong> <%= @report.pet.breed %></p>
          <p><strong>Color:</strong> <%= @report.pet.color %></p>
          <p><strong>Weight:</strong> <%= @report.pet.weight %></p>
          <p><strong>Age:</strong> <%= @report.pet.age %></p>
          <p><strong>Chip:</strong> <%= @report.pet.chip_id %></p>
        </div>
      </div>
        <div class="caption">

          <p><strong>Lost Date:</strong> <%= @report.date_of_loss.strftime("%m/%d/%Y") %></p>
          <p><strong>Lost Location:</strong> <%= @report.location %></p>
          <p><strong>Reward:</strong> <%= @report.reward %></p>
          <p><strong>Notes:</strong> <%= @report.notes %></p>
          <p><strong>Description:</strong> <%= @report.description %></p>
        </div>
  </div>
  </div>
</div>
<div>
  <p>
  <% if @report.user.is current_user %>
    <%= link_to 'Edit Lost Report', edit_report_path(@report), class: "link-btn-user edit-link link-btn" %>
  <% end %>
</div>
</div>

app/views/reports/show_contact_user.html.erb
<div class="col-sm-offset-3 col-sm-6 panel panel-default">
  <h1>Contact Pet Owner</h1>
<%= form_tag process_contact_user_path(@report), method: 'post' do %>
	<div class="form-group">
		Name<br />
    <%= text_field_tag :reporter_name, nil, placeholder: "Enter your name",  class: "form-control" %>
  </div>
	<div class="form-group">
		Email<br />
    <%= email_field_tag :email, nil, :placeholder =>'Enter your email address', class: "form-control" %>
  </div>
  <div class="form-group">
		Phone Number<br />
    <%= phone_field_tag :phone, nil, :placeholder => "Enter the best number to reach you", class: "form-control" %>
  </div>
	<div class="form-group">
		Message<br />
    <%= text_area_tag :message, nil, rows: 10, cols: 25, class: 'form-control', placeholder: "Enter a message for the owner" %>
  </div>
  <div class="form-group cap">
    <%= show_simple_captcha %>
  </div>
  <br>
  <div class="actions">
    <%= submit_tag "Send", class: "btn btn-large btn-primary"%>
  </div>
  <br>
<% end %>
</div>